### ISSUE TITLE
How can we use the .bin.gz file?

### ISSUE THREAD

**Issue by lan2720** [eyaler/word2vec-slim#1]
Hi, thanks for your work!

I want to use your word2vec slim version but how? When I try to decompress the .bin.gz file, it occurs error. 
![selection_126](https://cloud.githubusercontent.com/assets/5330101/18813686/d638036c-8334-11e6-8879-81b26d87168d.png)
I don't know how to use it. Any help? Thanks.

**Comment by eyaler** [comment]
1. The GoogleNews-vectors-negative300-SLIM.bin.gz is a ~270MB file stored on git with [git-lfs](https://git-lfs.github.com/). If you are cloning the repo you first need to install git-lfs.
2. Otherwise you can manually download the file, just make sure you do indeed have the real 270MB file. 
3. Please note you don't need to ungzip: `load_word2vec_format(filename, binary=True)` should just work.

**Comment by lan2720** [comment]
@eyaler Very clear. Thanks.
